### PR TITLE
Review the metrics in evolution WG issue_age

### PR DESCRIPTION
**Pull request by king-gao**
Signed-off-by: King Gao <king.gao@huawei.com>

review the translations into chinese :)

### CODE REVIEW

**Comment by germonprez** [comment]
could someone from @chaoss/chinese-translators give a second look to this PR? I've opened an issue that maybe we should have someone from @chaoss/chinese-translators be a maintainer on this repo to help.

**Comment by xiaoya-Esther** [comment]
Thanks for the review, King!

I agree that we need to maintain a terminology list first, that for an instance, if we want to call "the issue that opened" as "解决的issue" instead of“关闭的issue”, translations for all metrics that involves the expression need to be revised, too.

**Comment by king-gao** [comment]
yes, indeed , we must comprehensive the meaning of open issue, in the github\gitlab there is no "solution issue" 解决的issue , in the log there only close status when we click the close button. So there is “open issue” log, there is“close issue” log corresponding chinese are “新建/打开的issue ”和 “关闭的issue”。

**Comment by xiaoya-Esther** [comment]
Agree! it makes more sense to call it "关闭/打开的issue". But we may need to change the expression for **issue** in all the metrics accordingly, that seems to be a lot of work.

**Comment by germonprez** [comment]
If this is merged there will be cascading effects on the expression that is changed.

**Comment by xiaoya-Esther** [comment]
Thanks King, can we use this as a template to revise all the metrics under the Evolution Area?

**Pull request merged**
