### PR TITLE
Add translation of risk area

### PR DESCRIPTION
**Pull request by robekeane**

### CODE REVIEW

**Comment by germonprez** [comment]
Thanks! @xiaoya-Esther could you take a second look at these?

**Comment by yash2002109** [comment]
Thanks @robekeane!

I had some concerns with the README files of the focus areas. A template for these has been recently added in the governance repo - [governance/templates/focus-areas.md](https://github.com/chaoss/governance/blob/master/templates/focus-areas.md#template-for-wgfocus-areasfocus-area-namereadmemd)

There is also a PR in the actual Risk WG for this - <https://github.com/chaoss/wg-risk/pull/130>. 

I would suggest that we follow the template specified in the governance repo as the README standardization is also crucial to the [MARS project](https://github.com/chaoss/MARS).

**Comment by king-gao** [comment]
> Thanks @robekeane!
> 
> I had some concerns with the README files of the focus areas. A template for these has been recently added in the governance repo - [governance/templates/focus-areas.md](https://github.com/chaoss/governance/blob/master/templates/focus-areas.md#template-for-wgfocus-areasfocus-area-namereadmemd)
> 
> There is also a PR in the actual Risk WG for this - [chaoss/wg-risk#130](https://github.com/chaoss/wg-risk/pull/130).
> 
> I would suggest that we follow the template specified in the governance repo as the README standardization is also crucial to the [MARS project](https://github.com/chaoss/MARS).

thank you for your remind @yash2002109 ,that's really super helpful for us. we will update the file.

**Comment by robekeane** [comment]
> Thanks @robekeane!
> 
> I had some concerns with the README files of the focus areas. A template for these has been recently added in the governance repo - [governance/templates/focus-areas.md](https://github.com/chaoss/governance/blob/master/templates/focus-areas.md#template-for-wgfocus-areasfocus-area-namereadmemd)
> 
> There is also a PR in the actual Risk WG for this - [chaoss/wg-risk#130](https://github.com/chaoss/wg-risk/pull/130).
> 
> I would suggest that we follow the template specified in the governance repo as the README standardization is also crucial to the [MARS project](https://github.com/chaoss/MARS).

Hi Yash, 

Your reminder is very helpful, I will consider it. Thanks!

**Pull request closed without merging**
